services:
  nikolausers:
    restart: unless-stopped
    image: nikolausers:latest
    ports:
      - 127.0.0.1:6868:6868
    user: "33:33" # www-data on Debian
    environment:
      #SECRET_KEY: ""
      #DB_NAME: ""
      #DB_USER: ""
      #DB_PASSWORD: ""
      #DB_HOST: ""
      #EMAIL_HOST: ""
    volumes:
      - ./static:/app/static
